### ISSUE TITLE
checkly groups error 500

### ISSUE THREAD

**Issue by brampling** [checkly/checkly-cli#112]
![image](https://user-images.githubusercontent.com/18731474/145213366-227cf6d7-6d4d-447d-a0d1-261f3da867df.png)

**Comment by brampling** [comment]
![image](https://user-images.githubusercontent.com/18731474/145232607-098d348f-87ff-433b-8d15-7aa16007ebf3.png)

**Comment by ndom91** [comment]
@brampling can you double check you're on the latest `main`? 

Also which BE were you talking to? The `prod` one or a local copy? 

I just tested it against local BE as well as prod and both the `groups` cmd to list groups, as well as the `add group` cmd to create a new group worked for me.

**Comment by brampling** [comment]
@ndom91 I'm installing via `npm install -g @checkly/cli `.

`VERSION
  @checkly/cli/0.2.3 darwin-x64 node-v14.18.2`

**Comment by ndom91** [comment]
> @ndom91 I'm installing via `npm install -g @checkly/cli`.
> 
> `VERSION @checkly/cli/0.2.3 darwin-x64 node-v14.18.2`

Okay it looks like `0.2.3` is about 19 days old. There was a `0.2.4` published today though, give that a shot please :+1:

**Comment by brampling** [comment]
Updated, same issue:

`VERSION  @checkly/cli/0.2.4 darwin-x64 node-v14.18.2`

```
brampling@blair-checkly checkly-cli % checkly groups list


 ERROR  Request failed with status code 500                                                                                                          14:59:58

  at createError (/Users/brampling/.nvm/versions/node/v14.18.2/lib/node_modules/@checkly/cli/node_modules/axios/lib/core/createError.js:16:15)
  at settle (/Users/brampling/.nvm/versions/node/v14.18.2/lib/node_modules/@checkly/cli/node_modules/axios/lib/core/settle.js:17:12)
  at IncomingMessage.handleStreamEnd (/Users/brampling/.nvm/versions/node/v14.18.2/lib/node_modules/@checkly/cli/node_modules/axios/lib/adapters/http.js:269:11)
  at IncomingMessage.emit (events.js:412:35)
  at endReadableNT (internal/streams/readable.js:1334:12)
  at processTicksAndRejections (internal/process/task_queues.js:82:21)

    Error: Request failed with status code 500
```
