### ISSUE TITLE
Improve error handling for non-allowed runLocation

### ISSUE THREAD

**Issue by clample** [checkly/checkly-cli#399]
### Context
When a user runs `checkly test` with a non-supported run location, we currently print the full failed HTTP response for each check that runs:

```
$ npx checkly test --location does-not-exist

Running 4 checks in does-not-exist.

src/__checks__/home.check.js
  - 404 page
  - Homepage
  - Homepage - fetch stats
src/services/docs/__checks__/docs-search.spec.js
  - docs-search.spec.js

4 pending, 4 total

Scheduler failure AxiosError: Request failed with status code 400
    at settle (/Users/clample/projects/checkly-cli/package/node_modules/axios/dist/node/axios.cjs:1855:12)
    at IncomingMessage.handleStreamEnd (/Users/clample/projects/checkly-cli/package/node_modules/axios/dist/node/axios.cjs:2712:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_BAD_REQUEST',
... lot't of additional output...
```

### Proposal
We should print something like:
```
$ npx checkly test --location does-not-exist

Unable to run checks on unsupported location "does-not-exist". Supported locations are:

eu-central-1
us-west-2
...print all locations...
```

### Implementation
One question is whether we want to keep a list of all supported locations in the client, or if we want to rely on information from the backend. I think that relying on information from the backend would be better, since users can use new locations without needing to upgrade the checkly-cli version.

**Comment by tnolet** [comment]
@clample I think relying on the backend is also better.
