### ISSUE TITLE
bug: unclear error when `cli` section not set in Checkly config

### ISSUE THREAD

**Issue by clample** [checkly/checkly-cli#498]
### Node.js version

v16.17.0

### NPM version

8.15.0

### @checkly/cli version

@checkly/cli/0.3.14

### Steps to reproduce

Omit the `cli` section from a `checkly.config.js` file:

```
const config = {
    projectName: 'My First Checkly Project',
    logicalId: 'checkly-project-1',
    checks: {
        activated: true,
        muted: false,
        runtimeId: '2022.10',
        frequency: 10,
        locations: ['us-east-1', 'eu-west-1'],
        browserChecks: {
            testMatch: '**/*.spec.ts',
        },
    }
}

module.exports = config;
```

Then run `npx checkly test`

### What is expected?

Ideally, `npx checkly test` should pass. If the `cli` section is _really_ necessary, then there should be a clear validation error.

In particular, I think that we should aim for something like:
```
$ npx checkly test
    Required field `cli` was not found in the Checkly config file. 
```

### What is actually happening?

There is an obscure error:

```
$ npx checkly test
    TypeError: Cannot read properties of undefined (reading 'cli')
```

Running with `DEBUG=*` yields more info:
```
$ DEBUG=checkly* npx checkly test  
  checkly:@oclif/plugin-warn-if-update-available:hooks:init start (require) ...
  /node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update.js +0ms
  checkly:@oclif/plugin-warn-if-update-available:hooks:init done +2ms
  checkly:test init version: @oclif/core@2.0.7 argv: [] +0ms
TypeError: Cannot read properties of undefined (reading 'cli')
    at Test.run (.../node_modules/@checkly/cli/src/commands/test.ts:98:66)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Test._run (.../node_modules/@oclif/core/lib/command.js:107:22)
    at async Config.runCommand (.../node_modules/@oclif/core/lib/config/config.js:296:25)
```

### Any additional comments?

This is likely an issue for other fields in the `checkly.config.js` file as well. We should probably add some validation with clear errors here.

**Comment by clample** [comment]
Taking a closer look at the error, I think that I may have misinterpreted the error message in this issue.
```
TypeError: Cannot read properties of undefined (reading 'cli')
    at Test.run (.../node_modules/@checkly/cli/src/commands/test.ts:98:66)
```

That must mean that checklyConfig was undefined - not that checklyConfig was missing the cli property.
