### ISSUE TITLE
bug: local development environment is not working

### ISSUE THREAD

**Issue by nahuelon** [checkly/checkly-cli#615]
### Node.js version

v16.17.0

### NPM version

8.15.0

### @checkly/cli version

v0.4.9

### Steps to reproduce

Create a CLI project and execute the `test` command using the development environment: `<PATH>/bin/dev test`

### What is expected?

To parse the project and execute the checks using the local backend (`http://localhost:3000`).

### What is actually happening?

Resources can't be added to the project, throwing the following error:

```bash
Error: Error loading file /home/yosoy/checkly/sandbox/checkly-cli-sandbox/__check__/api.check.js
Error: Unable to create a construct 'ApiCheck' outside a Checkly CLI project.
    at Function.validateCreateConstruct (/home/yosoy/checkly/checkly-cli/packages/cli/src/constructs/project.ts:140:13)
    at new Construct (/home/yosoy/checkly/checkly-cli/packages/cli/src/constructs/construct.ts:10:13)
    at new Check (/home/yosoy/checkly/checkly-cli/packages/cli/src/constructs/check.ts:99:5)
    at new ApiCheck (/home/yosoy/checkly/checkly-cli/packages/cli/src/constructs/api-check.ts:254:5)
    at Object.<anonymous> (/home/yosoy/checkly/sandbox/checkly-cli-sandbox/__check__/api.check.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/home/yosoy/checkly/checkly-cli/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at loadJsFile (/home/yosoy/checkly/checkly-cli/packages/cli/src/services/util.ts:40:11)
    at loadAllCheckFiles (/home/yosoy/checkly/checkly-cli/packages/cli/src/services/project-parser.ts:80:23)
    at async parseProject (/home/yosoy/checkly/checkly-cli/packages/cli/src/services/project-parser.ts:63:3)
    at async Test.run (/home/yosoy/checkly/checkly-cli/packages/cli/src/commands/test.ts:125:21)
    at async Test._run (/home/yosoy/checkly/checkly-cli/node_modules/@oclif/core/lib/command.js:107:22)
    at async Config.runCommand (/home/yosoy/checkly/checkly-cli/node_modules/@oclif/core/lib/config/config.js:296:25)
```

### Any additional comments?

Docs in `CONTRIBUTING.md` must be adjusted too.

**Comment by nahuelon** [comment]
Already fixed in https://github.com/checkly/checkly-cli/pull/694
