### ISSUE TITLE
bug: Unable to create a construct 'ApiCheck' outside a Checkly CLI project.

### ISSUE THREAD

**Issue by anden-akkio** [checkly/checkly-cli#706]
### Node.js version

v20.1.0 (have tested 14.x.x as well)

### NPM version

9.6.4

### @checkly/cli version

@checkly/cli/0.4.13 darwin-arm64 node-v20.1.0

### Steps to reproduce

Honestly really not sure what caused this. I got this intermittently on CI/CD as well; this is the first time I've gotten it locally. This is the command that triggers it:

```
npx checkly test
```

### What is expected?

Runs my tests.

### What is actually happening?

Error: Unable to create a construct 'ApiCheck' outside a Checkly CLI project.
        at Session.validateCreateConstruct (/Users/andenacitelli/akkio/node_modules/checkly/dist/constructs/project.js:95:19)
        at new Construct (/Users/andenacitelli/akkio/node_modules/checkly/dist/constructs/construct.js:12:27)
        at new Check (/Users/andenacitelli/akkio/node_modules/checkly/dist/constructs/check.js:13:9)
        at new ApiCheck (/Users/andenacitelli/akkio/node_modules/checkly/dist/constructs/api-check.js:159:9)
        at /Users/andenacitelli/akkio/tests/__checks__/api/celery-queues.check.js:8:9
        at Array.map (<anonymous>)
        at module.exports (/Users/andenacitelli/akkio/tests/__checks__/api/celery-queues.check.js:7:46)
        at loadJsFile (/Users/andenacitelli/akkio/node_modules/@checkly/cli/dist/services/util.js:28:30)
        at loadAllCheckFiles (/Users/andenacitelli/akkio/node_modules/@checkly/cli/dist/services/project-parser.js:39:41)
        at async parseProject (/Users/andenacitelli/akkio/node_modules/@checkly/cli/dist/services/project-parser.js:27:5)

### Any additional comments?

My directory setup is as follows:

```
checkly.config.js
tests/
  __checks__/
    browser/
      test1.spec.js
      ...
    api/
      test1.check.js
```

My `checkly.config.js` looks like this:

```js
const { defineConfig } = require("checkly")

module.exports = defineConfig({
    projectName: 'Akkio',
    logicalId: 'akkio',
    checks: {
        activated: true,
        muted: false,
        runtimeId: '2022.10',
        frequency: 5,
        locations: ['us-east-1'],
        tags: ['website', 'api'],
        checkMatch: '**/__checks__/**/*.check.js',
        browserChecks: {
            frequency: 1,
            testMatch: '**/__checks__/**/*.spec.js',
        },
    },
    cli: {
        "runLocation": "us-east-1",
    }
})
```

Things I've tried:
- `checkly login`
- Delete and reinstall `node_modules` + `package-lock.json`
- `npx checkly test --config checkly.config.js`
- Uninstalling global version and running from a `package.json` script

**Comment by anden-akkio** [comment]
Fixed by basically nuking Checkly from my system and reinstalling. My suspicion is that the global install has issues finding the correct directory.

```
npm uninstall -g checkly @checkly/cli
npm uninstall checkly @checkly/cli
npm i checkly
checkly test
```
