### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by evdama** [checkly/checkly-cli#768]
Hi folks,

I'm doing a Sveltekit project on Vercel. Trying to add Checkly I'm running into an ES Module loading error:

```bash
sa@mst: ~/0/edm  |main U:2 ?:4 ✗| npx checkly login
✔ Do you want to log in or sign up to Checkly? › I want to log in with an existing Checkly account
✔ Do you want to open a browser window to continue with login? … yes
Successfully logged in as Mark
Welcome to the Checkly CLI
sa@mst: ~/0/edm  |main U:2 ?:4 ✗| checkly -v
checkly/4.0.8 darwin-x64 node-v20.3.0
sa@mst: ~/0/edm  |main U:2 ?:4 ✗| npx checkly test
Parsing your project... !
    Error: Error loading file /Users/sa/0/edm/checkly.config.ts
    Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/sa/0/edm/checkly.config.ts
    require() of ES modules is not supported.
    require() of /Users/sa/0/edm/checkly.config.ts from /Users/sa/0/edm/node_modules/checkly/dist/services/util.js is an ES module file as it is a .ts file 
    whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
    Instead change the requiring code to use import(), or remove "type": "module" from /Users/sa/0/edm/package.json.

        at createErrRequireEsm (/Users/sa/0/edm/node_modules/ts-node/dist-raw/node-internal-errors.js:46:15)
        at assertScriptCanLoadAsCJSImpl (/Users/sa/0/edm/node_modules/ts-node/dist-raw/node-internal-modules-cjs-loader.js:584:11)
        at Object.require.extensions.<computed> [as .ts] (/Users/sa/0/edm/node_modules/ts-node/src/index.ts:1610:5)
        at Module.load (node:internal/modules/cjs/loader:1113:32)
        at Function.Module._load (node:internal/modules/cjs/loader:960:12)
        at Module.require (node:internal/modules/cjs/loader:1137:19)
        at require (node:internal/modules/helpers:121:18)
        at /Users/sa/0/edm/node_modules/checkly/src/services/util.ts:65:54
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async loadTsFile (/Users/sa/0/edm/node_modules/checkly/src/services/util.ts:65:33)    
sa@mst: ~/0/edm  |main U:2 ?:4 ✗|
```
It's a Sveltekit project running on Vercel. Here's the package.json
```json
{
  "name": "edm",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "test": "playwright test",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "test:unit": "vitest",
    "lint": "prettier --plugin-search-dir . --check . && eslint .",
    "format": "prettier --plugin-search-dir . --write ."
  },
  "devDependencies": {
    "@playwright/test": "^1.35.1",
    "@skeletonlabs/skeleton": "^1.7.1",
    "@sveltejs/adapter-vercel": "^3.0.1",
    "@sveltejs/kit": "^1.20.4",
    "@tailwindcss/forms": "^0.5.3",
    "@tailwindcss/typography": "^0.5.9",
    "@typescript-eslint/eslint-plugin": "^5.60.0",
    "@typescript-eslint/parser": "^5.60.0",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.43.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-svelte": "^2.31.0",
    "postcss": "^8.4.24",
    "prettier": "^2.8.8",
    "prettier-plugin-svelte": "^2.10.1",
    "svelte": "^3.59.1",
    "svelte-check": "^3.4.3",
    "tailwindcss": "^3.3.2",
    "tslib": "^2.5.3",
    "typescript": "latest",
    "vite": "^4.3.9",
    "vitest": "^0.32.2",
    "checkly": "latest",
    "ts-node": "latest"
  },
  "type": "module",
  "dependencies": {
    "@vercel/analytics": "^1.0.1"
  }
}
```

My tsconfig.json looks like this

```json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true
	}
}
```
and then `.svelte-kit/tsconfig.json`

```json
{
	"compilerOptions": {
		"paths": {
			"$lib": [
				"../src/lib"
			],
			"$lib/*": [
				"../src/lib/*"
			]
		},
		"rootDirs": [
			"..",
			"./types"
		],
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"preserveValueImports": true,
		"lib": [
			"esnext",
			"DOM",
			"DOM.Iterable"
		],
		"moduleResolution": "node",
		"module": "esnext",
		"target": "esnext",
		"ignoreDeprecations": "5.0"
	},
	"include": [
		"ambient.d.ts",
		"./types/**/$types.d.ts",
		"../vite.config.ts",
		"../src/**/*.js",
		"../src/**/*.ts",
		"../src/**/*.svelte",
		"../tests/**/*.js",
		"../tests/**/*.ts",
		"../tests/**/*.svelte"
	],
	"exclude": [
		"../node_modules/**",
		"./[!ambient.d.ts]**",
		"../src/service-worker.js",
		"../src/service-worker.ts",
		"../src/service-worker.d.ts"
	]
}
```

And here's the `checkly.config.ts` as installed by `npm create checkly`

```ts
import { defineConfig } from 'checkly'

/**
 * See https://www.checklyhq.com/docs/cli/project-structure/
 */
const config = defineConfig({
  /* A human friendly name for your project */
  projectName: 'edm',
  /** A logical ID that needs to be unique across your Checkly account,
  * See https://www.checklyhq.com/docs/cli/constructs/ to learn more about logical IDs.
  */
  logicalId: 'edm',
  /* An optional URL to your Git repo */
  repoUrl: 'https://github.com/checkly/checkly-cli',
  /* Sets default values for Checks */
  checks: {
    /* A default for how often your Check should run in minutes */
    frequency: 10,
    /* Checkly data centers to run your Checks as monitors */
    locations: ['us-east-1', 'eu-west-1'],
    /* An optional array of tags to organize your Checks */
    tags: ['mac'],
    /** The Checkly Runtime identifier, determining npm packages and the Node.js version available at runtime.
     * See https://www.checklyhq.com/docs/cli/npm-packages/
     */
    runtimeId: '2023.02',
    /* A glob pattern that matches the Checks inside your repo, see https://www.checklyhq.com/docs/cli/using-check-test-match/ */
    checkMatch: '**/__checks__/**/*.check.ts',
    browserChecks: {
      /* A glob pattern matches any Playwright .spec.ts files and automagically creates a Browser Check. This way, you
      * can just write native Playwright code. See https://www.checklyhq.com/docs/cli/using-check-test-match/
      * */
      testMatch: '**/__checks__/**/*.spec.ts',
    },
  },
  cli: {
    /* The default datacenter location to use when running npx checkly test */
    runLocation: 'eu-west-1',
    /* An array of default reporters to use when a reporter is not specified with the "--reporter" flag */
    reporters: ['list'],
  },
})

export default config
```

Any ideas how to solve this? Is there maybe a checkly discord channel for quick questions such as this one?

_Originally posted by @evdama in https://github.com/checkly/checkly-cli/issues/619#issuecomment-1598186913_

**Comment by tnolet** [comment]
hey @evdama thanks for reporting this. We don't have a cut and clear solution for this but will look into this again ASAP

**Comment by evdama** [comment]
Correct me if I'm wrong please: it means that it's currently not possible to use checkly with a Sveltekit project yes? I did a standard install of both, Sveltekit and Checkly without touching either code or config files and the result is as shown above.

**Comment by tnolet** [comment]
@evdama we have not tested it yet with a Svelte project. It seems to pretty specific to that framework, as we are using checkly fine with nuxt, next etc. We will look at it ASAP

**Comment by evdama** [comment]
Hi folks, any update on this one?

**Comment by tnolet** [comment]
Hey @evdama sorry, no update yet. Again, it's seems to only pop up with Svelte and we have been able to create the time to do a deep dive on that.

**Comment by clample** [comment]
Hi @evdama,

I think that we have a fix now. The CLI had issues importing the Checkly config file when projects use ECMAScript Modules (`"type": "module"` in `package.json`) and TypeScript.

Could you please try again using `checkly` version `0.0.0-pr.804.7a3174d`? The fix will be added to a normal release soon, but for now we made this prerelease.

**Comment by tnolet** [comment]
@evdama we just released this version under on the main branch. It's `v4.0.13` or just `@latest`
