### ISSUE TITLE
bug: checkly login produces error 

### ISSUE THREAD

**Issue by geoffharcourt** [checkly/checkly-cli#856]
### Node.js version

18.16.0

### NPM version

9.7.1

### @checkly/cli version

0.0.7

### Steps to reproduce

When I run `npx checkly login` or `yarn checkly login` I get an error.

### What is expected?

I'm authenticated with Checkly.

### What is actually happening?

```
❯ npx checkly login
      ┏━━━━━━━━━━━━━━━━━━━━━━━┓
      ┃                       ┃
      ┃                       ┃
      ┃      checkly cli      ┃
      ┃                       ┃
      ┃                       ┃
      ┗━━━━━━━━━━━━━━━━━━━━━━━┛
/Users/geoff/commonlit/commonlit/node_modules/glob/sync.js:28
    throw new Error('must provide pattern')
          ^

Error: must provide pattern
    at new GlobSync (/Users/geoff/commonlit/commonlit/node_modules/glob/sync.js:28:11)
    at Function.globSync [as sync] (/Users/geoff/commonlit/commonlit/node_modules/glob/sync.js:23:10)
    at getFiles (file:///Users/geoff/commonlit/commonlit/node_modules/checkly-cli/src/check-definitions.js:11:28)
    at getCheckGroupDefinitions (file:///Users/geoff/commonlit/commonlit/node_modules/checkly-cli/src/check-definitions.js:50:17)
    at main (file:///Users/geoff/commonlit/commonlit/node_modules/checkly-cli/src/index.js:48:32)
    at file:///Users/geoff/commonlit/commonlit/node_modules/checkly-cli/bin/index.js:5:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.16.0
```

### Any additional comments?

This also happens if I run `checkly test` or anything that's not `checkly --version`

**Comment by tnolet** [comment]
@geoffharcourt seems like you are running quite an old version 😅. Can you upgrade to our latest & greatest?

We are at 4.1.0 now and the package name is now just "checkly" not the namespaced "@checkly/cli" 

https://www.npmjs.com/package/checkly

You should have the login working after that.
